services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
    depends_on:
      - db
